/*
   Copyright 2024-2025 LinChenjun

   本程序是自由软件
   修改和/或再分发依照 GNU GPL version 3 (or any later version)

*/

#ifndef __XHCI_MEM_H__
#define __XHCI_MEM_H__

#define XHCI_PG_SZIE 0x1000

// Memory Alignment and Boundary Definitions
#define XHCI_DEVICE_CONTEXT_INDEX_MAX_SIZE      2048
#define XHCI_DEVICE_CONTEXT_MAX_SIZE            2048
#define XHCI_INPUT_CONTROL_CONTEXT_MAX_SIZE     64
#define XHCI_SLOT_CONTEXT_MAX_SIZE              64
#define XHCI_ENDPOINT_CONTEXT_MAX_SIZE          64
#define XHCI_STREAM_CONTEXT_MAX_SIZE            16
#define XHCI_STREAM_ARRAY_LINEAR_MAX_SIZE       1024 * 1024 // 1 MB
#define XHCI_STREAM_ARRAY_PRI_SEC_MAX_SIZE      4096
#define XHCI_TRANSFER_RING_SEGMENTS_MAX_SIZE    1024 * 64   // 64 KB
#define XHCI_COMMAND_RING_SEGMENTS_MAX_SIZE     1024 * 64   // 64 KB
#define XHCI_EVENT_RING_SEGMENTS_MAX_SIZE       1024 * 64   // 64 KB
#define XHCI_EVENT_RING_SEGMENT_TABLE_MAX_SIZE  1024 * 512  // 512 KB
#define XHCI_SCRATCHPAD_BUFFER_ARRAY_MAX_SIZE   248
#define XHCI_SCRATCHPAD_BUFFERS_MAX_SIZE        4096

#define XHCI_DEVICE_CONTEXT_INDEX_BOUNDARY      4096
#define XHCI_DEVICE_CONTEXT_BOUNDARY            4096
#define XHCI_INPUT_CONTROL_CONTEXT_BOUNDARY     4096
#define XHCI_SLOT_CONTEXT_BOUNDARY              4096
#define XHCI_ENDPOINT_CONTEXT_BOUNDARY          4096
#define XHCI_STREAM_CONTEXT_BOUNDARY            4096
#define XHCI_STREAM_ARRAY_LINEAR_BOUNDARY       4096
#define XHCI_STREAM_ARRAY_PRI_SEC_BOUNDARY      4096
#define XHCI_TRANSFER_RING_SEGMENTS_BOUNDARY    1024 * 64   // 64 KB
#define XHCI_COMMAND_RING_SEGMENTS_BOUNDARY     1024 * 64   // 64 KB
#define XHCI_EVENT_RING_SEGMENTS_BOUNDARY       1024 * 64   // 64 KB
#define XHCI_EVENT_RING_SEGMENT_TABLE_BOUNDARY  4096
#define XHCI_SCRATCHPAD_BUFFER_ARRAY_BOUNDARY   4096
#define XHCI_SCRATCHPAD_BUFFERS_BOUNDARY        4096

#define XHCI_DEVICE_CONTEXT_INDEX_ALIGNMENT     64
#define XHCI_DEVICE_CONTEXT_ALIGNMENT           64
#define XHCI_INPUT_CONTROL_CONTEXT_ALIGNMENT    64
#define XHCI_SLOT_CONTEXT_ALIGNMENT             32
#define XHCI_ENDPOINT_CONTEXT_ALIGNMENT         32
#define XHCI_STREAM_CONTEXT_ALIGNMENT           16
#define XHCI_STREAM_ARRAY_LINEAR_ALIGNMENT      16
#define XHCI_STREAM_ARRAY_PRI_SEC_ALIGNMENT     16
#define XHCI_TRANSFER_RING_SEGMENTS_ALIGNMENT   64
#define XHCI_COMMAND_RING_SEGMENTS_ALIGNMENT    64
#define XHCI_EVENT_RING_SEGMENTS_ALIGNMENT      64
#define XHCI_EVENT_RING_SEGMENT_TABLE_ALIGNMENT 64
#define XHCI_SCRATCHPAD_BUFFER_ARRAY_ALIGNMENT  64
#define XHCI_SCRATCHPAD_BUFFERS_ALIGNMENT       4096

#endif